modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="create_central_kitchen"
version="${file.jarVersion}"
displayName="Create: Central Kitchen"
displayURL="https://www.curseforge.com/minecraft/mc-mods/create-central-kitchen"
logoFile="logo.png"
#credits=""
authors="LimonBlaze, MarbleGate and Etherwood"
description='''
An add-on for Create, providing automation support for your kitchen.
'''

[[dependencies.create_central_kitchen]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_central_kitchen]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_central_kitchen]]
    modId="create"
    mandatory=true
    versionRange="[0.5.0.i,)"
    ordering="AFTER"
    side="BOTH"

# Must load after these optional dependencies

[[dependencies.create_central_kitchen]]
    modId="environmental"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.create_central_kitchen]]
    modId="upgrade_aquatic"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"